name: youtube_downloader


services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    entrypoint: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - redis_data:/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./start.sh", "bot"]
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - media:/app/media
    depends_on:
      - db
      - redis

  admin-panel:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./start.sh", "admin_panel"]
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - media:/app/media
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "./start.sh", "celery" ]
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - admin-panel

volumes:
  postgres_data:
  redis_data:
  media: